const mainColors = {
  greyblack: '#9BA0A6',
  blue2: '#4552CB',
  grey1: '#BBC3CE',
  grey2: '#DADADA',
  grey3: '#50555C',
  grey4: '#F9F9FA',
  borderGrey: '#F0F0F8',
  blue1: '#456CD7',
  white1: '#FFFFFF',
  black1: '#070821',
  white2: '#FBFBFE',
  garis: '#BDBDBD',
  bluewhite: '#F8FBFF',
  orange1: '#F1A852',
  green1: '#27AE60',
};

export const colors = {
  primary: mainColors.blue2,
  secondary: mainColors.greyblack,
  white: 'white',
  black: 'black',
  text: {
    primary: mainColors.black1,
    secondary: mainColors.grey2,
    tree: mainColors.grey1,
    for: mainColors.grey3,
    five: mainColors.green1,
    MenuinActive: mainColors.grey1,
    MenuActive: mainColors.blue2,
  },
  button: {
    primary: {
      background: mainColors.green,
      text: 'white',
    },
  },
  Bg: {
    primary: mainColors.blue1,
    secondary: mainColors.white1,
    tree: mainColors.borderGrey,
    for: mainColors.white2,
    five: mainColors.garis,
    six: mainColors.bluewhite,
    seven: mainColors.orange1,
    eight: mainColors.grey4,
  },
  border: mainColors.borderGrey,
  cardLight: mainColors.green2,
};
